name: Auto-merge PRs to production

on:
  pull_request:
    branches:
      - production

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge PR to production
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git merge --no-ff --no-edit FETCH_HEAD
          git push origin production
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}